---
output: 
  md_document:
    variant: markdown_github
---

## Trabajo en equipo para la asignatura "Big Data"

Repo utilizado para elaborar el trabajo individual para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2020-2021. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-20-21-web/>.


La versión final del trabajo puede visualizarse en: <https://nosan5.github.io/trabajo_BigData/>. 


El presentre trabajo **"ESTUDIO SOBRE EL MERCADO DE TRABAJO"** ha sido realizado por Noelia Sánchez para la asignatura de "Big Data"

En él se analizar el **desempleo**, dado que me parece un problema económico importante de tratar.

En especial, me centraré en la **Tasa de desempleo (en España) para diferentes grupos de edad, sexo y Comunidades Autónomas**.

Además, compararé la tasa de paro de nuestro país ci¡on la que presentan otros países de la Unión Europea. 

Por último, analizaré brevemente algunas cuestiones que me parecen interesante, como las **% mujeres directivas** que hay en los países de la OCDE y la **brecha salarial** existente.


